name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Check C++20 Support
        run: |
          if ! g++ -std=c++20 -dM -E - < /dev/null | grep -q "__cplusplus.*202002L"; then
            echo "Current GCC version does not support C++20"
            exit 1
          fi
          gcc --version

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Configure CMake
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
          else
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          fi

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C Release --output-on-failure